<a href="https://colab.research.google.com/github/ThomasVanHecke/Objectgerichte-softwareontwikkeling/blob/main/chapter1/chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1: Introduction to python

In order to acces extra functionalities from external libraries, you need to iport them. These imports should be done at the start of the file to get a good overview of which packages are imported. Run the code below to import the packages:

In [4]:
# We use the 'as' keyword to rename the imports to shorter words so we have to write less in the code.
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
import math

## 1.3 Working with vectors and matrices

### 1.3.1 Scalars and vectors

In [14]:
# Create a new variable x
x= np.array([10,9 ,8 ,7 ,6, 5 ,4, 3, 2, 1])

# Add 12 to a new array y
y=np.array([22, 21, 20, 19, 18, 17, 16 ,15, 14, 13])

# determine the length of the vector
lengte = len(y)
print("de lengte van array y is: " + str(lengte))

# sum of the elements
som= sum(x)
print("De som van array x is:" + str(som))

# the min of the sin of the elements
sinus_x= np.sin(x)  #berekend de sinus van elk element
minimum_sinus= np.min(sinus_x)
print("min van de sin: " + str(minimum_sinus))

# The sum of elements 4 to 10
som4tot10 = np.sum(y[4:10])
print("de som van element 4 tot en met 10 van array  y is : " + str(som4tot10))

# make vector z
z= np.arange(200 , 0 , -1) #np.arange( start, stop, step)

# Cummulative sums of z
som1 = np.sum(z[0:20])
print("antwoord som1: " + str(som1))
som2 = np.sum(z[0:30])
print("antwoord som2: " + str(som2) )
som3 = np.sum(z[0:40])
print("antwoord som3: " + str(som3))

# Calculate the formula


# Bereken de term tussen haakjes
term = (1/12) - (1/(5 * 25)) - (1/(28 * 27)) - (1/(72 * 29))

# Vermenigvuldig met 24
term = 24 * term

# Bereken 3 * sqrt(3) / 4
term1 = (3 * np.sqrt(3)) / 4

# Tel de termen op en trek pi af
a = term1 + term - np.pi

# Print het resultaat met 15 beduidende cijfers
print(f"{a:.15e}")

de lengte van array y is: 10
De som van array x is:55
min van de sin: -0.9589242746631385
de som van element 4 tot en met 10 van array  y is : 93
antwoord som1: 3810
antwoord som2: 5565
antwoord som3: 7220
-7.779483253273023e-02


### 1.3.2 Matrices

#### Question 1: Random Matrix

In [17]:
# Make matrix A
A= np.random.random((4,5)) #matrix met 4 rijen en 5 kolommen, willekeurige waarde tss 0 en 1
x= A[:,2] #vector x met middelste kolom dus index 2
y= A[3,:] #vector met laatste rij dus index 3

print(A)
print(x)
print(y)
# Make matrix B
B= np.random.random((1000 , 2))

[[0.95403452 0.63390012 0.67402689 0.11595166 0.97492451]
 [0.49167274 0.16488352 0.35984658 0.41779154 0.34832956]
 [0.19137227 0.19054308 0.33281282 0.87025042 0.45372961]
 [0.340882   0.78653377 0.97828916 0.08806582 0.34591291]]
[0.67402689 0.35984658 0.33281282 0.97828916]
[0.340882   0.78653377 0.97828916 0.08806582 0.34591291]


#### Question 2: Rotation Matrix

In [21]:
# 10° matrix
theta_degre= 10
theta_rad= np.radians(theta_degre) #converteer naar radialen
R = np.array([
    [np.cos(theta_rad), -np.sin(theta_rad)],
    [np.sin(theta_rad), np.cos(theta_rad)]
])
print(R.round(6))

# 45° matrix
theta_degre1= 45
theta_rad1= np.radians(theta_degre1) #converteer naar radialen
R1 = np.array([
    [np.cos(theta_rad1), -np.sin(theta_rad1)],
    [np.sin(theta_rad1), np.cos(theta_rad1)]
])
print(R1.round(6))

# 60° matrix
theta_degre2= 60
theta_rad2= np.radians(theta_degre2) #converteer naar radialen
R2 = np.array([
    [np.cos(theta_rad2), -np.sin(theta_rad2)],
    [np.sin(theta_rad2), np.cos(theta_rad2)]
])
print(R2.round(6))

# Rotate point

# Definieer de hoeken in graden
theta_deg = [10, 45, 60]

# Puntsvector m
m = np.array([1, 1])

# Functie om rotatiematrix te berekenen
def rotation_matrix(theta_deg):
    theta_rad = np.radians(theta_deg)
    return np.array([
        [np.cos(theta_rad), -np.sin(theta_rad)],
        [np.sin(theta_rad), np.cos(theta_rad)]
    ])

# Berekeningen voor elke hoek
for theta in theta_deg:
    # Rotatiematrix
    R = rotation_matrix(theta)

    # Geroteerd punt
    m_rot = R @ m

    # Determinant
    det = np.linalg.det(R)

    # Inverse
    R_inv = np.linalg.inv(R)

    # Print resultaten
    print(f"\nVoor θ = {theta}°:")
    print(f"Rotatiematrix R({theta}°):")
    print(R.round(6))
    print(f"Geroteerd punt m_rot = R({theta}°) * m: [{m_rot[0]:.6f}, {m_rot[1]:.6f}]^T")
    print(f"Determinant van R({theta}°): {det:.6f}")
    print(f"Inverse van R({theta}°):")
    print(R_inv.round(6))


# Determinant


# Inverse



[[ 0.984808 -0.173648]
 [ 0.173648  0.984808]]
[[ 0.707107 -0.707107]
 [ 0.707107  0.707107]]
[[ 0.5      -0.866025]
 [ 0.866025  0.5     ]]

Voor θ = 10°:
Rotatiematrix R(10°):
[[ 0.984808 -0.173648]
 [ 0.173648  0.984808]]
Geroteerd punt m_rot = R(10°) * m: [0.811160, 1.158456]^T
Determinant van R(10°): 1.000000
Inverse van R(10°):
[[ 0.984808  0.173648]
 [-0.173648  0.984808]]

Voor θ = 45°:
Rotatiematrix R(45°):
[[ 0.707107 -0.707107]
 [ 0.707107  0.707107]]
Geroteerd punt m_rot = R(45°) * m: [0.000000, 1.414214]^T
Determinant van R(45°): 1.000000
Inverse van R(45°):
[[ 0.707107  0.707107]
 [-0.707107  0.707107]]

Voor θ = 60°:
Rotatiematrix R(60°):
[[ 0.5      -0.866025]
 [ 0.866025  0.5     ]]
Geroteerd punt m_rot = R(60°) * m: [-0.366025, 1.366025]^T
Determinant van R(60°): 1.000000
Inverse van R(60°):
[[ 0.5       0.866025]
 [-0.866025  0.5     ]]


#### Question 3: Systems

In [22]:

import numpy as np

# Definieer de matrix A en vector b
A = np.array([[1, -3, 0],
              [-1, -1, 2],
              [5, 2, -1]])

b = np.array([0, 5200, 6400])

# Los het stelsel op met np.linalg.solve
x = np.linalg.solve(A, b)

# Print de resultaten
print(f"An bezit: AC{x[0]:.2f}")
print(f"Ben bezit: AC{x[1]:.2f}")
print(f"Carlos bezit: AC{x[2]:.2f}")

An bezit: AC1800.00
Ben bezit: AC600.00
Carlos bezit: AC3800.00


## 1.4 Functions

### 1.4.1 Question 1: Some Simple Functions

In [23]:
# Function celcius_to_farenheit
def celcius_to_farenheit(celcius):

    # Add your conversion code here
    farenheit = (celcius * 9/5)+ 32


    return farenheit # the farenheit value

In [24]:
# Check the results
print(celcius_to_farenheit(0))
print(celcius_to_farenheit(20))
print(celcius_to_farenheit(37))
print(celcius_to_farenheit(100))

32.0
68.0
98.6
212.0


In [25]:
# Absolute function
def absolute_function(getal):
  absolute_waarde= abs(getal)

  return absolute_waarde


In [26]:
# Validate the results
print(absolute_function(-10))
print(absolute_function(0))
print(absolute_function(np.pi))


10
0
3.141592653589793


In [27]:
# Swap function
def swap_function(getal1, getal2):
  getal1, getal2 = getal2, getal1

  return getal1, getal2

In [28]:
# Validate the results
print(swap_function(10,20))


(20, 10)


### 1.4.2 Question 2: Distances and included angles of a triangle

In [29]:
# Solve triangle function

def SolveTriangle(A, B, C):
    # Bereken vectoren
    AB = np.array(B) - np.array(A)
    AC = np.array(C) - np.array(A)
    BC = np.array(C) - np.array(B)

    # Bereken lengtes van de zijden
    lAB = np.linalg.norm(AB)
    lAC = np.linalg.norm(AC)
    lBC = np.linalg.norm(BC)

    # Bereken hoeken met de wet van cosinussen
    # α (hoek bij A)
    cos_alpha = (lAC**2 + lAB**2 - lBC**2) / (2 * lAC * lAB)
    alpha = np.degrees(np.arccos(np.clip(cos_alpha, -1.0, 1.0)))

    # β (hoek bij B)
    cos_beta = (lAB**2 + lBC**2 - lAC**2) / (2 * lAB * lBC)
    beta = np.degrees(np.arccos(np.clip(cos_beta, -1.0, 1.0)))

    # γ (hoek bij C)
    cos_gamma = (lAC**2 + lBC**2 - lAB**2) / (2 * lAC * lBC)
    gamma = np.degrees(np.arccos(np.clip(cos_gamma, -1.0, 1.0)))

    # Retourneer resultaten
    return {
        'lAB': lAB,
        'lAC': lAC,
        'lBC': lBC,
        'alpha': alpha,
        'beta': beta,
        'gamma': gamma
    }



In [30]:
# Validate the results
# Voer de functie uit voor de gegeven driehoek
A = (0, 0)
B = (8, 0.5)
C = (2, 1.5)

result = SolveTriangle(A, B, C)

# Print resultaten
print(f"lAB = {result['lAB']:.3f}")
print(f"lAC = {result['lAC']:.3f}")
print(f"lBC = {result['lBC']:.3f}")
print(f"α = {result['alpha']:.3f}°")
print(f"β = {result['beta']:.3f}°")
print(f"γ = {result['gamma']:.3f}°")

lAB = 8.016
lAC = 2.500
lBC = 6.083
α = 33.294°
β = 13.039°
γ = 133.668°


## 1.5 Control Structures

### 1.5.1 Question 1: Fibbonacci

In [ ]:
# Fibbonacci function


In [ ]:
# Validate the results


### 1.5.2 Question 2: Did I pass?

In [ ]:
# Passed function


In [ ]:
# Validate the results


## 1.6 Plot

2D-plots worden meestal gemaakt door x- en y-coördinaten op te geven.
Matplotlib verbindt de ingevoerde punten met lijnen om continue curve te simuleren.

Een reeks x-waarden worden meestal gegenereed mbv np.linspace functie (zie api)

Bijhorende array van y-waarden wordt dan berekend met de x-waarden als input

Zie het voorbeeld hieronder:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# np.linspace maakt een array van 200 waarden evenredig verdeeld tussen [0,2*pi]
x = np.linspace(0, 2 * np.pi, 200)
# y is hier ook een array van 200 getallen (nl. de sinus van x)
y = np.sin(x)

#basis plot syntax; bekijk de api documentatie voor de functie subplots en de return values
fig, ax = plt.subplots()
ax.plot(x, y)

#laatste output wordt hieronder weergegeven
plt.ylabel('Scores')
plt.title('sinus')
plt.show()

### 1.7.3 Opgave 1: Amerikaanse bevolking

Het Amerikaanse bevolkingscijfer kan gemodelleerd worden in de tijd a.d.h.v. een bepaalde functie.
Enkele stappen:

    - bepaal je x-waarden (van 1790 tem 2025)
    - bepaal de bijhorende y-waarden (tip definieer de functie zoals gegeven in de opdracht en gebruik deze in je code)
    - plot deze functie

    - vervolgens voeg je de extra gevraagde zaken toe. functie hit (axes = return value van plt.subplots()):
        - axes.set_xlabel
        - axes.axvline
        - axes.set_xticks
        - 'markevery' optional argument bij de functie ax.plot

In [ ]:
def predict_population(year):
    return #functie

### 1.7.2 Opgave 2 : Combineer gegevens

Matplotlab laat ook toe om figuren naast en onder elkaar te schikken om zo tot een mooie layout
te komen. Bekijk de functie subplot voor meer informatie. In deze oefening maak je gebruik van
deze functionaliteit en zal je verschillende grafiektypes gebruiken.

In [ ]:
#uitlezen data
fcdata = np.genfromtxt("faalkosten_FCdata.txt",delimiter = ',')
fcmateriaal = np.genfromtxt("faalkosten_materiaal.txt",delimiter = ',')/1000
fcplaatsing = np.genfromtxt("faalkosten_plaatsing.txt",delimiter = ',')/1000
fctechnieken = np.genfromtxt("faalkosten_technieken.txt",delimiter = ',')/1000

fig1=plt.figure()




### 1.7.3 Opgave 3 : Plotten in 3D
In Geomaticatoepassingen kom je regelmatig in contact met 3D data. Een typisch voorbeeld
daarvan is een digitale hoogtekaart of -model (DEM) dat bijvoorbeeld aangemaakt wordt met
behulp van luchtlaserscanning. Matlab beschikt ook hier over interessante functionaliteit om
deze data te behandelen en te visualiseren

Tips contour plot:
    - axes.contour()
    - axes.clabel()
    - fig.colorbar()

In [ ]:
#3D Surface plot


In [ ]:
# Coloured DEM Plot


In [ ]:
#100m Contour Line


In [ ]:
# Countour line + values
